spring.application.name=apptienda
spring.datasource.url=jdbc:mysql://localhost:3306/tiendaropa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

