spring.application.name=apptienda

#Puerto de Railway
server.port=${SERVER_PORT:8080}
#Configuracion de la base de datos 
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuracion de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.properties.hibernate.format_sql=true 					

#Clave secreta JWT
apptienda.secreto.jwt=${APPTIENDA_SECRETO_JWT}
apptienda.tiempo.expiracion.jwt=${APPTIENDA_TIEMPO_EXPIRACION_JWT}