spring.application.name=apptienda
server.port=8088


#Configuracion de la base de datos 
spring.datasource.url=jdbc:mysql://localhost:3306/tiendaropa?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

#Configuracion de JPA y Hibernate
spring.jpa.hibernate.ddl-auto=update											
spring.jpa.properties.hibernate.format_sql=true 					
